language: android

before_script:
- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-19
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-22
  - sys-img-armeabi-v7a-android-19

jdk:
  - oraclejdk8

after_success:
  - .utility/initiate-publish.sh

env:
  global:
  - secure: gNr1SEJoYKRxBap0ihqollmQiG9iTx3L5i5w7AW6fFdgv5JN8srAVaoyQZScuFsd9H2murqTNmVuYLbL3M0YtegOF4h6EMicAKemtNAdAmLMYKG1QCTVkKCM8fdI6tpfvVp7nq8EdFPWDAUruJnEnC8zfrZ+4TdRehucMzjV74c=
  - secure: kbMhn10M49EHvopZwQ2H+DuNZGp6gRhjJsgta1XQ/2kBOK7iSJoPTpklgAdIQJ/vNgYTgagtRyK/3AqcE8SV7iyyTWIXCIF/u5Jz/57TTeWhYJRUCncu0P9fLim+wPzst52FWLOvSXT/9NADCygQPtRioKztqswaQtzFExDLM9o=
